"""add mp fields to sales

Revision ID: 0851c7b4c645
Revises: 3cb811099404
Create Date: 2026-03-16 23:54:04.656895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0851c7b4c645'
down_revision: Union[str, Sequence[str], None] = '3cb811099404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('mp_preference_id', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('mp_payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'mp_payment_id')
    op.drop_column('sales', 'mp_preference_id')
    # ### end Alembic commands ###
